version: 0.2
phases:
  build:
    commands:
       - echo Entered the build phase ...
        - mvn clean package
    post_build:
      commands:
             -echo build completely successfully
    artifacts:
            files:
                -target/crud-example-0.0.1-SNAPSHOT.jar

